# Generated by Django 3.2.13 on 2022-05-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField(default=99)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Electronics', 'Electronics'), ('Cutlery', 'Cutlery'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Others', 'Others')], max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
            ],
        ),
    ]
