# Generated by Django 3.2.13 on 2022-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveBigIntegerField(default=99),
        ),
    ]
