# Generated by Django 3.2.13 on 2022-05-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
